# Generated by Django 5.1.4 on 2024-12-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teeapp', '0002_assignment_link_lesson_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permormance',
            name='marks',
        ),
        migrations.AddField(
            model_name='permormance',
            name='percentage',
            field=models.IntegerField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
